server:
  port : 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UnlaPermisos?serverTimezone=GMT-3
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: 
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
spring.security.user.name: administrador 
spring.security.user.password: admin123   
spring.security.user.roles: ADMINISTRADOR 